metadata:
  net_type: api0lw8421ew1repw10poly4l
  region: l
  rho: 0.85
  temp: 0.9
  num_saved: '010'
  dpt: 10

system:
  seed: 34952
  deterministic: true
  force_cuda: true

model:
  single_parnet_type: transformer_type
  multi_parnet_type: gnn_identity
  readout_net_type: mlp_type
  trans_layer: 2
  gnn_layer: 2
  nnode: 128
  pw4mb_nnodes: 128
  pw_output_dim: 3
  d_model: 256
  nhead: 8
  net_dropout: 0.0
  edge_attention: true
  init_weights: relu

simulation:
  tau_long: 0.05
  saved_pair_steps: 5
  window_sliding: 8
  tau_traj_len_factor: 8

grid:
  ngrid: 12
  b:
    - 0.2
  a:
    - 0

optimizer:
  optimizer: Adam
  maxlr: 0.00001
  grad_clip: 0.5
  tau_init: 1

loss:
  loss_weights:
    - 0
    - 0.125
    - 0
    - 0.25
    - 0
    - 0.5
    - 0
    - 1
  poly_deg: 4
  rthrsh: 0.67
  ew: 1
  repw: 10

data:
  train_file: ../thumbnail_data/n64lt0.1stpstraj180_l_dpt100.pt
  valid_file: ../thumbnail_data/n64lt0.1stpstraj180_l_dpt100.pt
  test_file: ../thumbnail_data/n64lt0.1stpstraj180_l_dpt100.pt
  train_pts: 10
  valid_pts: 10
  test_pts: 10
  batch_size: 2

eval:
  npar: 64
  ml_steps: 10
  append_strike: 2
  gamma: 20

run:
  ckpt_path: ./results/baseline_run/baseline000020.pth
  save_dir: ./results/test_folder/
  nitr: 500
  tau_short: 0.0001
  append_strike: 500
