metadata:
  net_type: api0lw8421ew1repw10poly4l
  region: l

system:
  seed: 34952
  deterministic: true
  force_cuda: true

model:
  single_parnet_type: transformer_type
  multi_parnet_type: gnn_identity
  readout_net_type: mlp_type
  trans_layer: 2
  gnn_layer: 2
  nnode: 128
  pw4mb_nnodes: 128
  pw_output_dim: 3
  d_model: 256
  nhead: 8
  net_dropout: 0.0
  edge_attention: true
  init_weights: relu
  tau_init: 1

simulation:
  tau_long: 0.05
  saved_pair_steps: 5
  window_sliding: 8
  tau_traj_len_factor: 8
  allowed_window_sliding:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    - 9
    - 10
    - 12
    - 14
    - 16

grid:
  ngrid: 12
  b:
    - 0.2
  a:
    - 0

optimizer:
  optimizer: Adam
  maxlr: 0.00001
  grad_clip: 0.5

loss:
  loss_weights:
    - 0
    - 0.125
    - 0
    - 0.25
    - 0
    - 0.5
    - 0
    - 1
  ew: 1
  repw: 10
  rthrsh: 0.7
  poly_deg: 4

data:
  train_file: ../thumbnail_data/n64lt0.1stpstraj180_l_dpt100.pt
  valid_file: ../thumbnail_data/n64lt0.1stpstraj180_l_dpt100.pt
  test_file: ../thumbnail_data/n64lt0.1stpstraj180_l_dpt100.pt
  dpt_train: 10
  dpt_valid: 10
  dpt_test: 10
  batch_size: 2

run:
  start_epoch: 0
  end_epoch: 20
  loadfile: null
  save_dir: ./results/baseline_run
  nitr: 500
  tau_short: 0.0001
  append_strike: 500
  ckpt_interval: 1
  val_interval: 1
  verb: 1
